### ISSUE TITLE
wrong types used in fixedpoint-header

### ISSUE THREAD

**Issue by questor** [electronicarts/EAStdC#1]
Hi,
thanks for releasing all the code as open-source, I've found a (most likely) copy'n'paste error:

https://github.com/electronicarts/EAStdC/blob/master/include/EAStdC/EAFixedPoint.h#L997

shouldn't the macro be (notice the TypeDef instead of an actual type)
template<> EASTDC_API int32_t FP_PASCAL TypeDef::FixedMul(const int32_t a, const int32_t b); \
?

**Comment by rparolin** [comment]
Good catch!  Did you want to submit a PR?

**Comment by questor** [comment]
I've tried to generate a compile-error for the missing defines, but it seems the defines are not neccessary at all? (https://github.com/questor/EAStdC)   besides: there seems to be some left-over, for example in the test fixed-point multiplication for 24.8 format is available, but not in the implementation of the fixed-point class itself, would be good to have it available in general of course in combination with testcases.
